// <auto-generated />
using System;
using Labb1_ResturantBookingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1_ResturantBookingSystem.Migrations
{
    [DbContext(typeof(BookingSystemContext))]
    [Migration("20240830202415_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            CustomerId = 1,
                            Date = new DateTime(2024, 8, 31, 22, 24, 15, 375, DateTimeKind.Local).AddTicks(138),
                            NumberOfPeople = 0,
                            TableId = 1,
                            Time = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            BookingId = 2,
                            CustomerId = 2,
                            Date = new DateTime(2024, 9, 1, 22, 24, 15, 375, DateTimeKind.Local).AddTicks(195),
                            NumberOfPeople = 0,
                            TableId = 2,
                            Time = new TimeSpan(0, 19, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Malin Nyberg",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fredrik Jansson",
                            PhoneNumber = "0707654321"
                        });
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfDish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MenuId");

                    b.ToTable("menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            IsAvailable = false,
                            NameOfDish = "Spaghetti Bolognese",
                            Price = 12.99m
                        },
                        new
                        {
                            MenuId = 2,
                            IsAvailable = false,
                            NameOfDish = "Caesar Salad",
                            Price = 9.99m
                        },
                        new
                        {
                            MenuId = 3,
                            IsAvailable = false,
                            NameOfDish = "Pizza Vesuvio",
                            Price = 8.99m
                        },
                        new
                        {
                            MenuId = 4,
                            IsAvailable = false,
                            NameOfDish = "Swedish Meatballs - Italian style",
                            Price = 10.99m
                        });
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            NumberOfSeats = 4,
                            TableNumber = 1
                        },
                        new
                        {
                            TableId = 2,
                            NumberOfSeats = 2,
                            TableNumber = 2
                        },
                        new
                        {
                            TableId = 3,
                            NumberOfSeats = 6,
                            TableNumber = 3
                        },
                        new
                        {
                            TableId = 4,
                            NumberOfSeats = 4,
                            TableNumber = 4
                        },
                        new
                        {
                            TableId = 5,
                            NumberOfSeats = 8,
                            TableNumber = 5
                        });
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("Labb1_ResturantBookingSystem.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1_ResturantBookingSystem.Models.Table", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Labb1_ResturantBookingSystem.Models.Table", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
